alias l='ls -al'
alias lt='ls -t | head'
alias toclip='xclip -sel clip'
alias fzto='fzf-tmux | xclip -sel clip'
alias fzf='fzf-tmux'
alias opbo='open $(fzf-tmux)'
alias sleep='date && sleep'

alias c='xclip'
alias ctrlc='xclip -selection clipboard'
alias v='xclip -o'
